FILE={arg: base}
BASE=$(basename ${FILE})
OTHER={arg: files}

DEPLATE=deplate

OFLAGS=
DFLAGS={arg: options}

HTML_DIR=html
HTML_PLUS=
HTML_DFLAGS=$\{HTML_PLUS\} -d $\{HTML_DIR\} -f html

XHTML_DIR=$\{HTML_DIR\}
XHTML_PLUS=$\{HTML_PLUS\}
XHTML_DFLAGS=$\{XHTML_PLUS\} -d $\{XHTML_DIR\} -f xhtml11m

WEBSITE_DIR=website
WEBSITE_DFLAGS=$\{HTML_PLUS\} -d $\{WEBSITE_DIR\} -f htmlsite

PHP_DIR=php
PHP_DFLAGS=$\{HTML_PLUS\} -d $\{PHP_DIR\} -f phpsite

TEX_DIR=tex
TEX_DFLAGS=-d $\{TEX_DIR\} -f latex

TEXT_DIR=plain
TEXT_DFLAGS=-d $\{TEXT_DIR\} -f plain

DBK_DIR=docbook
DBK_DFLAGS=-d $\{DBK_DIR\} -f dbk-article

REF_DIR=$\{DBK_DIR\}
REF_DFLAGS=-d $\{REF_DIR\} -f dbk-ref

LATEX_FLAGS=-interaction=nonstopmode
PDFLATEX_FLAGS=$\{LATEX_FLAGS\}
BIBTEX_FLAGS=

SWEAVE_DIR=$\{TEX_DIR\}
SWEAVE_DFLAGS=-d $\{TEX_DIR\} -f sweave

copy_images=if ls *.{jpg,jpeg,png,gif} 2> /dev/null; then cp -uv *.{jpg,jpeg,png,gif} $(1); fi
copy_css=if ls *.css 2> /dev/null; then cp -vu *.css $(1); fi

.PHONY: view show cleantex website makefile pdfclean dviclean \
	dbk html pdf tex text man \
	prepare_website prepare_html prepare_xhtml prepare_text prepare_php prepare_dbk \
	prepare_tex prepare_ref prepare_dvi prepare_pdf

default: html

prepare_website:
	mkdir -p $\{WEBSITE_DIR\}
	$(call copy_images,"$\{WEBSITE_DIR\}")
	$(call copy_css,"$\{WEBSITE_DIR\}")

prepare_html:
	mkdir -p $\{HTML_DIR\}
	$(call copy_images,"$\{HTML_DIR\}")
	$(call copy_css,"$\{HTML_DIR\}")

prepare_xhtml:
	mkdir -p $\{XHTML_DIR\}
	$(call copy_images,"$\{XHTML_DIR\}")
	$(call copy_css,"$\{XHTML_DIR\}")

prepare_text:
	mkdir -p $\{TEXT_DIR\}

prepare_php:
	mkdir -p $\{PHP_DIR\}
	$(call copy_images,"$\{PHP_DIR\}")
	$(call copy_css,"$\{PHP_DIR\}")

prepare_dbk:
	mkdir -p $\{DBK_DIR\}cp -uv *.{jpg,jpeg,png,gif} $(1) || echo ... ignore errorcp -uv *.{jpg,jpeg,png,gif} $(1) || echo ... ignore error
	$(call copy_images,"$\{DBG_DIR\}")

prepare_tex:
	mkdir -p $\{TEX_DIR\}
	$(call copy_images,"$\{TEX_DIR\}")

prepare_ref:
	mkdir -p $\{REF_DIR\}

prepare_dvi:

prepare_pdf:

prepare_sweave: prepare_tex

define postprocess_sweave
if [ "$\{CYGWIN\}" ]; then dos2unix $1; fi
endef

